"""B4_PLANNER_REPLAN — Planner replan with Critic oracle ranking (Phase 4 D-23).

Per CONTEXT.md D-23: B4 calls Critic.rank_candidates() to pick the best
replan from N candidates generated by the Planner.

B4 respects Phase 3 contracts:
  - try_claim: atomic claim-or-fail before firing
  - cancel_event check: return None if recovery orchestrator cancelled this branch
  - max_cycles gate: orchestrator enforces max 2 cycles (not B4's concern)

P21 MITIGATION: Critic ranks external oracle outputs; never self-critiques.

Failure modes tracked for RL training + future improvements.
"""
from __future__ import annotations

from typing import TYPE_CHECKING, Optional

import structlog

from cua_overlay.recovery.branches import BranchBase

if TYPE_CHECKING:
    from cua_overlay.actions.channels.base import ChannelOutcome
    from cua_overlay.actions.idempotency import IdempotencyTokenStore
    from cua_overlay.cognition.critic import Critic
    from cua_overlay.cognition.planner import Planner
    from cua_overlay.persist.session_writer import SessionWriter
    from cua_overlay.recovery.classifier import FailureCtx
    from cua_overlay.state.causal_dag import ActionCanonical
    from cua_overlay.state.graph import StateGraph


class B4RecoveryBranch(BranchBase):
    """Planner replan with Critic oracle ranking (D-23).

    Generates N candidate replans via Planner, then calls Critic.rank_candidates()
    to pick the best one using pairwise comparison. Used to recover from cognitive
    errors when B3's world model prediction insufficient.
    """

    name: str = "B4_PLANNER_REPLAN"

    def __init__(
        self,
        idempotency_store: IdempotencyTokenStore,
        session_writer: SessionWriter,
        planner: Planner,
        critic: Critic,
        num_candidates: int = 3,
    ):
        """Initialize B4 recovery branch.

        Args:
            idempotency_store: IdempotencyTokenStore for try_claim (T-3-05)
            session_writer: SessionWriter for event emission
            planner: Planner instance for generating candidates
            critic: Critic instance for ranking candidates
            num_candidates: Number of replan candidates to generate (default 3)
        """
        super().__init__(
            name=self.name,
            _idempotency=idempotency_store,
            _session_writer=session_writer,
        )
        self._planner = planner
        self._critic = critic
        self._num_candidates = num_candidates
        self._log = structlog.get_logger()
        self._cancel_event = None  # Will be set by recovery orchestrator

    def set_cancel_event(self, event) -> None:
        """Set the cancellation event (called by orchestrator).

        Per Phase 3 contract: branches check cancel_event before firing.
        """
        self._cancel_event = event

    async def attempt(
        self, failure_ctx: FailureCtx
    ) -> Optional[ChannelOutcome]:
        """Attempt planner replan + critic ranking (D-23).

        D-23 flow:
        1. Check cancel_event (Phase 3 contract) — return None if set
        2. Try to claim action_id (T-3-05 idempotency)
        3. Generate N candidate replans (call planner N times with different prompts)
        4. Call critic.rank_candidates(candidates) → top-1
        5. Return ranked ActionCanonical or None on failure

        Args:
            failure_ctx: FailureCtx with failed action, current state, etc.

        Returns:
            None (B4 doesn't fire channels; it returns a ranked replanned action
            for the recovery orchestrator to re-inject into the race).
        """
        bundle_id = failure_ctx["bundle_id"]
        target_key = failure_ctx["target_key"]
        action_id = failure_ctx.get("action_id", target_key)
        failed_action: ActionCanonical = failure_ctx.get("action", None)
        current_state: StateGraph = failure_ctx.get("state", None)

        await self._emit_event(
            {
                "event": "branch_attempt",
                "branch": "B4_PLANNER_REPLAN",
                "target_key": target_key,
                "bundle_id": bundle_id,
            }
        )

        # Phase 3 contract: check cancel_event (D-24)
        if self._cancel_event and self._cancel_event.is_set():
            self._log.debug(
                "b4.cancelled",
                action_id=action_id,
                target_key=target_key,
            )
            await self._emit_event(
                {
                    "event": "branch_failed",
                    "branch": "B4_PLANNER_REPLAN",
                    "reason": "cancel_event_set",
                    "action_id": action_id,
                }
            )
            return None

        # T-3-05: Try to claim the action
        if not await self._try_claim(action_id, "B4_planner_replan"):
            self._log.debug(
                "b4.claim_failed",
                action_id=action_id,
                target_key=target_key,
            )
            await self._emit_event(
                {
                    "event": "branch_failed",
                    "branch": "B4_PLANNER_REPLAN",
                    "reason": "claim_failed",
                    "action_id": action_id,
                }
            )
            return None

        # Validate context
        if failed_action is None or current_state is None:
            self._log.warning(
                "b4.missing_context",
                action_id=action_id,
                has_action=failed_action is not None,
                has_state=current_state is not None,
            )
            await self._emit_event(
                {
                    "event": "branch_failed",
                    "branch": "B4_PLANNER_REPLAN",
                    "reason": "missing_context",
                    "action_id": action_id,
                }
            )
            return None

        try:
            # D-23: Generate N candidate replans with different prompts
            self._log.info(
                "b4.generate_candidates_start",
                action_id=action_id,
                num_candidates=self._num_candidates,
            )

            candidates = []
            prompts = self._build_candidate_prompts(failed_action, target_key)

            for i, prompt in enumerate(prompts[: self._num_candidates]):
                try:
                    plan_candidate = await self._planner.plan_action(
                        task_description=prompt,
                        current_state=current_state,
                    )

                    if plan_candidate and plan_candidate.steps:
                        first_step = plan_candidate.steps[0]

                        # Coerce to ActionCanonical if needed (Phase 4 allows dicts)
                        if isinstance(first_step, dict):
                            from cua_overlay.state.causal_dag import ActionCanonical
                            import time

                            candidate_action = ActionCanonical(
                                id=f"{action_id}_b4_candidate_{i}",
                                step_idx=0,
                                kind=first_step.get("kind", "READ"),
                                target_key=first_step.get("target_key", target_key),
                                action_type=first_step.get("action_type", "click"),
                                payload=first_step.get("payload", {}),
                                timestamp_ns=int(time.monotonic_ns()),
                                session_id=failure_ctx.get("session_id", "unknown"),
                            )
                        else:
                            candidate_action = first_step

                        candidates.append(candidate_action)
                except Exception as e:
                    self._log.warning(
                        "b4.candidate_generation_error",
                        action_id=action_id,
                        candidate_idx=i,
                        error=str(e),
                    )

            if not candidates:
                self._log.debug(
                    "b4.no_candidates_generated",
                    action_id=action_id,
                )
                await self._emit_event(
                    {
                        "event": "branch_failed",
                        "branch": "B4_PLANNER_REPLAN",
                        "reason": "no_candidates_generated",
                        "action_id": action_id,
                    }
                )
                return None

            # D-23: Use Critic to rank candidates (P21 mitigation)
            self._log.info(
                "b4.critic_rank_start",
                action_id=action_id,
                num_candidates=len(candidates),
            )

            best_candidate, confidence = await self._critic.rank_candidates(
                current_state=current_state,
                candidates=candidates,
                criterion="planner_replan",
            )

            self._log.info(
                "b4.critic_ranked",
                action_id=action_id,
                best_candidate_id=best_candidate.id,
                confidence=confidence,
            )

            await self._emit_event(
                {
                    "event": "branch_success",
                    "branch": "B4_PLANNER_REPLAN",
                    "action_id": action_id,
                    "best_candidate_id": best_candidate.id,
                    "critic_confidence": confidence,
                    "num_candidates": len(candidates),
                }
            )

            # Return the best-ranked candidate
            return best_candidate  # type: ignore

        except Exception as e:
            self._log.error(
                "b4.ranking_error",
                action_id=action_id,
                error=str(e),
                exc_info=True,
            )
            await self._emit_event(
                {
                    "event": "branch_failed",
                    "branch": "B4_PLANNER_REPLAN",
                    "reason": "ranking_error",
                    "error": str(e),
                    "action_id": action_id,
                }
            )
            return None

    def _build_candidate_prompts(
        self, failed_action: ActionCanonical, target_key: str
    ) -> list[str]:
        """Build N different prompts for planner to generate diverse candidates.

        Each prompt has a slightly different angle on the recovery problem.
        """
        prompts = [
            # Candidate 1: Direct retry
            (
                f"The action {failed_action.action_type} on target {target_key} failed. "
                f"Generate a plan to retry the same action using a different approach."
            ),
            # Candidate 2: Alternative path
            (
                f"The action {failed_action.action_type} on target {target_key} failed. "
                f"Generate a plan using an alternative method or different target."
            ),
            # Candidate 3: Escalation
            (
                f"The action {failed_action.action_type} on target {target_key} failed. "
                f"Generate a fallback plan that works around the failed target."
            ),
        ]
        return prompts
